// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCMn65_0Y6J_ch-qkK9FCw1FDigCNQSQ',
    appId: '1:481034128522:web:813b6c7f42e92ebb1b7173',
    messagingSenderId: '481034128522',
    projectId: 'ecomm-490a4',
    authDomain: 'ecomm-490a4.firebaseapp.com',
    storageBucket: 'ecomm-490a4.appspot.com',
    measurementId: 'G-FYJEYNFLVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBgpuPw8wMys5z6swvB66s8sktvMpJQx0',
    appId: '1:481034128522:android:7cf45d934212561b1b7173',
    messagingSenderId: '481034128522',
    projectId: 'ecomm-490a4',
    storageBucket: 'ecomm-490a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Ecdm52vglGDw189TAVT6CvWIe-R69Ng',
    appId: '1:481034128522:ios:fb23e6f973e551781b7173',
    messagingSenderId: '481034128522',
    projectId: 'ecomm-490a4',
    storageBucket: 'ecomm-490a4.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Ecdm52vglGDw189TAVT6CvWIe-R69Ng',
    appId: '1:481034128522:ios:fb23e6f973e551781b7173',
    messagingSenderId: '481034128522',
    projectId: 'ecomm-490a4',
    storageBucket: 'ecomm-490a4.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
